#spring.servlet.multipart.max-file-size是单个文件上传大小限制，max-request-size是请求整体上传大小限制
server:
  port: 6789
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  datasource:
    url: jdbc:mysql://localhost:3306/fan?serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
